# GitHub Pages Jekyll configuration
title: "Cash Cleaner Optimizer"
description: "Optimize cash packaging into bundles and blocks"
url: "https://your-username.github.io"
baseurl: "/cash-cleaner-optimizer"

# Exclude files from processing
exclude:
  - README.md
  - .github/

# Include files
include:
  - index.html

# Disable Jekyll processing (since we have a static HTML file)
plugins: []
kramdown:
  input: GFM
  hard_wrap: false 